# Stolen from capitaomorte/yasnippet
language: emacs

env:
  - "EMACS=emacs24"

install:
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs24-nox;
    fi

script: $EMACS -batch -L . -l ert -l tests.el -f ert-run-tests-batch-and-exit
